web:
    build: ./web
    command: python app.py
    ports:
        - "9090:8080"
    volumes:
        - ./web:/code
    links:
        - mongo
mongo:
    image: mongo:3.0
    ports:
        - "27019:27017"
    command: --smallfiles --quiet --logpath=/dev/null
